---
# tasks file for grafana
- name: 1.0 Ensure /etc/apt/keyrings directory exists
  file:
    path: "{{ grafana_ensure_keyrings }}"
    state: directory
    mode: '0755'
  become: true

- name: 1.1 Download and dearmor Grafana GPG key
  ansible.builtin.get_url:
    url: "{{ grafana_download_pgp }}"
    dest: "{{ grafana_dest_gpg }}"
    mode: '0644'
  become: true

- name: 1.2 Convert Grafana GPG key to binary format
  ansible.builtin.command:
    cmd: "{{ grafana_convert_gpg }}"
  args:
    creates: "{{ grafana_ensure_keyrings }}/grafana.gpg"
  become: true

- name: 1.3 Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "{{ grafana_repo }}"
    state: present
    filename: grafana
  become: true

- name: 1.4 Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: 1.5 Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
  become: true

- name: 1.6 Ensure grafana-server is started
  ansible.builtin.service:
    name: grafana-server
    state: started
  become: true

- name: 1.7 Check grafana version
  ansible.builtin.command: 
    cmd: "{{ grafana_check_version }}"
  register: grafana_version

- name: 1.8 Debug check grafana version
  debug:
    msg: "{{ grafana_version }}"

- name: 1.9 Check grafana service start
  shell: "{{ grafana_service_status }}"
  register: grafana_status

- name: 1.10 Debug check grafana service start
  debug:
    msg: "{{ grafana_status }}"