---
# tasks file for check_system
- name: 1.0 Gather system information and check internet connectivity
  ansible.builtin.setup:
    gather_subset:
      - 'network'

- name: 1.1 Gethering and display block
  block:  
    - name: 1.1.1 Display hostname
      debug: 
        msg: "Hostname: {{ ansible_hostname }}"

    - name: 1.1.2 Display operation system family
      debug: 
        msg: "OS Name: {{ ansible_os_family }}" 

    - name: 1.1.3 Display operating system version
      debug:
        msg: "OS Version: {{ ansible_distribution_version }}"

    - name: 1.1.4 Display tital RAM size
      debug: 
        msg: "Total RAM: {{ ansible_memtotal_mb }} MB"

    - name: 1.1.5 List all users on the system
      command: getent passwd
      register: user_list

    - name: 1.1.6 Display users in system
      debug:
        msg: "Users: {{ user_list.stdout_lines | map('split', ':') | map('first') | list }}"

    - name: 1.1.7 Display IP address
      debug:
        msg: "Host: {{ inventory_hostname }}, IP: {{ ansible_default_ipv4.address if ansible_default_ipv4 is defined else 'No default IPv4 address' }}" 
  become: true
