---
# tasks file for addusers
- name: Ensure what {{ addusers_group }} group exists
  ansible.builtin.group:
    name: somegroup
    state: present

- name: Add users to {{ addusers_group }} group
  user:
    name: "{{ item[0] }}"
    password: "{{ item[1] }}"
    state: present
    groups: "{{ addusers_group }}"
  with_items: "{{ addusers_users }}"
  become: true