---
# defaults file for 1—Å
srvr1c_version: "8.3.23.2236"
srvr1c_setup_run_file: setup-full-{{ srvr1c_version }}-x86_64.run
srvr1c_service_name: srv1cv8-{{ srvr1c_version }}@.service

srvr1c_locales:
  - ru_RU.CP1251
  - ru_RU.UTF-8
srvr1c_default_locale: ru_RU.UTF-8

srvr1c_debug_status: true

# srvr1c_postgresql_version: "16.2-3.1C"
# srvr1c_postgresql_tar: "postgresql_16.2_3.1C_amd64_deb.tar.bz2"
srvr1c_postgresql_install_apps:
  - libldap-2.4-2 
  - libpq5
  - libssl1.1
  - postgresql
  - postgresql-common
  - postgresql-client
  - postgresql-client-common