---
# 1c_install file for prometheus
- name: 1.0 Check timezone
  shell: "{{ srvr1c_shell_check_timezone }}"
  register: stdout_timedatectl

- name: 1.1 Set timezone
  shell: "{{ srvr1c_shell_timezone }}"
  become: true
  when: stdout_timedatectl.stdout != "Europe/Moscow"

- name: 1.2 Set need locale
  block:
    - name: 1.2.1 Add needs locale in {{ srvr1c_locales_files.locale_gen }} (for Debian/Ubuntu)
      ansible.builtin.lineinfile:
        path: "{{ srvr1c_locales_files.locale_gen }}"
        regexp: "^#?({{ item }})"
        line: "{{ item }}"
        state: present
      loop: "{{ srvr1c_locales }}"
      become: true
      when: ansible_os_family == "Debian"

    - name: 1.2.2 Add needs locale in {{ srvr1c_locales_files.locale_conf }} (for RedHat)
      ansible.builtin.lineinfile:
        path: "{{ srvr1c_locales_files.locale_conf }}"
        line: "{{ item }}"
        state: present
      loop: "{{ srvr1c_locales }}"
      become: true
      when: ansible_os_family == "RedHat"

    - name: 1.2.3 Generate locale
      ansible.builtin.command: locale-gen "{{ item }}"
      loop: "{{ srvr1c_locales }}"
      become: true
      when: ansible_os_family == "Debian"

- name: 1.3 Set locale as default
  block:
    - name: 1.3.1 Refresh var LANG in {{ srvr1c_locale_path }} (for Debian/Ubuntu)
      ansible.builtin.lineinfile:
        path: "{{ srvr1c_locale_path }}"
        regexp: "^LANG="
        line: "LANG={{ srvr1c_default_locale }}"
        create: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: 1.3.2 Refresh var LANG in {{ srvr1c_locales_files.locale_conf }} (for RedHat)
      ansible.builtin.lineinfile:
        path: "{{ srvr1c_locales_files.locale_conf }}"
        regexp: "^LANG="
        line: "LANG={{ srvr1c_default_locale }}"
        create: yes
      become: true
      when: ansible_os_family == "RedHat"

- name: 1.4 Check all aviable locale
  shell: locale -a
  register: available_locales

- name: 1.5 Check locale as default
  shell: locale
  register: default_locales

# - name: "1.6 Extract {{ srvr1c_run_files}}"
#   ansible.builtin.unarchive:
#     src: "/tmp/{{ srvr1c_artifactory_directory}}/{{ srvr1c_run_files}}"
#     dest: "/tmp/{{ srvr1c_artifactory_directory}}/"
#     remote_src: yes
 
- name: "1.6 Extract {{ srvr1c_run_files }}"
  shell: tar -xzvf "/tmp/{{ srvr1c_artifactory_directory }}/{{ srvr1c_run_files }}" -C "/tmp/{{ srvr1c_artifactory_directory }}/"

- name: "1.7 Set executable permissions on {{ srvr1c_setup_run_file }}"
  ansible.builtin.file:
    path: "/tmp/{{ srvr1c_artifactory_directory}}/{{ srvr1c_setup_run_file }}"
    mode: '0777'
    state: file
  become: true

# - name: "1.8 Install {{ srvr1c_setup_run_file }} with language selection"
#   shell: "{{ srvr1c_shell_install_1c }}"
#   become: true

- name: 1.9 Move service file
  template:
    src: '{{ item[0] }}'
    dest: '{{ item[1] }}'
    owner: root
    group: root
    mode: 0750
  loop:
    - "{{ srvr1c_templates_service }}"
    - "{{ srvr1c_templates_ras_service }}"
  
# - name: 1.10 Create simlink on 1c
#   shell: "{{ item }}"
#   loop:
#     - "{{ srvr1c_shell_create_ras_simlink }}"
#     - "{{ srvr1c_shell_create_server_simlink }}"
#   become: true

- name: 1.11 Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: "1.12 Enable and start srv1cv8-{{ srvr1c_version }}@default.service and rassrv1cv8@default.service service"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - "srv1cv8-{{ srvr1c_version }}@default.service"
    - "rassrv1cv8@default.service"
  become: true

- name: 1.13 Add rac to PATH in .bashrc
  block:
    - name: Write rac dir to PATH
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH=$PATH:/opt/1cv8/x86_64/8.3.23.2236'
        insertafter: EOF
        state: present
    
    - name: Apply changes by sourcing .bashrc
      ansible.builtin.shell: |
        source ~/.bashrc
      args:
        executable: /bin/bash
  become: true

- name: "1.14 Check status srv1cv8-{{ srvr1c_version }}@default.service"
  shell:  "systemctl status srv1cv8-{{ srvr1c_version }}@default.service | grep Active"
  register: status_1c_server_service

- name: "1.15 Check status rassrv1cv8@default.service"
  shell:  "systemctl status rassrv1cv8@default.service | grep Active"
  register: status_1c_server_ras_service

- name: 1.16 Debug system info
  debug:
    msg: 
      - "Timezone {{ stdout_timedatectl.stdout }}"
      - "Default locales: {{ default_locales.stdout }}"
      - "1C Server service status: {{ status_1c_server_service.stdout }}"
      - "1C Server RAS status: {{ status_1c_server_ras_service.stdout }}"
  when: srvr1c_debug_status  == true