---
# main file for prometheus
- name: 1.0 Install 1C
  include_tasks: 1c_install.yml
  # vars:
  #   ansible_python_interpreter: "{{ prometheus_python_interpreter }}"

- name: 2.0 Install PostgreSQL
  include_tasks: postgresql_install.yml
  # vars:
  #   ansible_python_interpreter: "{{ prometheus_python_interpreter }}"

# - name: 3.0 Configure prometheus scraping
#   include_tasks: prometheus_scraping.yml
  # vars:
  #   ansible_python_interpreter: "{{ prometheus_python_interpreter }}"