---
# postgresql_install file for prometheus
- name: 2.1 Add repository 
  block: 
    - name: 2.1.1 Add the bionic main universe repository
      ansible.builtin.apt_repository:
        repo: "{{ srvr1c_add_repository }}"
        state: present

    - name: 2.1.2 Update the apt package index
      ansible.builtin.apt:
        update_cache: yes
      
    - name: 2.1.3 Add GPG key from Ubuntu keyserver
      ansible.builtin.apt_key:
        keyserver: "{{ srvr1c_add_repository_keyserver }}"
        id: "{{ srvr1c_add_repository_id }}"
  ignore_errors: true
  become: true

- name: 2.2 Check installed packages
  command: dpkg -l
  register: installed_packages

- name: 2.3 Install and hold pg apps
  block: 
    - name: 2.3.1 Install apps
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        force: yes
      loop: "{{ srvr1c_postgresql_install_apps }}"
      when: item not in installed_packages.stdout

    - name: 2.3.2 Fix broken dependencies
      command: "{{ srvr1c_shell_fix_broken_package }}"

    - name: 2.3.3 Hold packages
      shell: "apt-mark hold {{ item }}"
      loop: "{{ srvr1c_postgresql_install_apps }}"
  ignore_errors: true
  become: true

- name: 2.4 Check hold packages
  command: "{{ srvr1c_shell_check_hold_package }}"
  register: list_hold_packages

- name: 2.5 Debug hold package
  debug:
    msg: "{{ list_hold_packages.stdout }}"