---
# postgresql_install file for prometheus
- name: 2.0 Check if bionic main universe repository is present
  ansible.builtin.command: apt-cache policy
  register: apt_policy

- name: 2.1 Add repository 
  block: 
    - name: 2.1.1 Add the bionic main universe repository
      ansible.builtin.apt_repository:
        repo: 'deb http://ru.archive.ubuntu.com/ubuntu/ bionic main universe'
        state: present

    - name: 2.1.2 Update the apt package index
      ansible.builtin.apt:
        update_cache: yes
      
    - name: 2.1.3 Add GPG key from Ubuntu keyserver
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 3B4FE6ACC0B21F32
  when: "'bionic main universe' not in apt_policy.stdout"
  ignore_errors: true
  become: true

- name: 2.2 Check installed packages
  command: dpkg -l
  register: installed_packages

- name: 2.3 Install and hold pg apps
  block: 
    - name: 2.3.1 Install apps
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        force: yes  # Используйте force для принудительной установки
      loop: "{{ srvr1c_postgresql_install_apps }}"
      
    - name: 2.3.2 Fix broken dependencies
      command: apt-get install -f

    - name: 2.3.3 Hold packages
      apt:
        name: "{{ srvr1c_postgresql_install_apps }}"
        state: held

  when: item not in installed_packages.stdout
  ignore_errors: true
  become: true

- name: 2.4 Check hold packages
  command: apt-mark showhold
  register: list_hold_packages

- name: 2.5 Debug hold package
  debug:
    msg: "{{ list_hold_packages }}"