---
# configurate_prometheus file for prometheus
- name: 1.0 Create Prometheus user and group
  block:
    - name: 1.0.1 Create Prometheus group
      ansible.builtin.group:
        name: prometheus
        system: yes

    - name: 1.0.2 Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        system: yes
        shell: /sbin/nologin
        group: prometheus
  become: yes

- name: 1.1 Create /etc/prometheus directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: 1.2 Create /var/lib/prometheus directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'

- name: 1.3 Download prometheus
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp/
  ignore_errors: yes
  with_items: "{{ prometheus_download_url }}"
  become: true

- name: 1.4 Extract the binare prometheus files 
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /opt/
    remote_src: yes
  with_items: "{{ prometheus_archive }}"
  become: true

- name: Check exist temp file
  ansible.builtin.stat:
    path: "{{ prometheus_archive }}"
  register: prometheus_file

- name: Remove temp file
  ansible.builtin.file:
    path: "{{ prometheus_archive }}"
    state: absent
  when: prometheus_file.stat.exists

- name: 1.5 Move binary & Set Owner
  block: 
    - name: 1.5.1 Copy promtool binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      with_items: "{{ prometheus_bin_file }}"
      ignore_errors: true

    - name: 1.5.2 Change ownership of /usr/local/bin/
      ansible.builtin.file:
        path: "/usr/local/bin/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        state: file
      with_items: "{{ prometheus_bin_file }}"
  become: true

- name: 1.6 Move the Configuration Files & Set Owner
  block: 
    - name: 1.6.1 Copy prometheus binary to /etc/prometheus
      ansible.builtin.copy:
        src: "/opt/prometheus-2.43.0.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      with_items: "{{ prometheus_conf_file }}"
      ignore_errors: true

    - name: 1.6.2 Change ownership of /etc/prometheus
      ansible.builtin.file:
        path: /etc/prometheus
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: 1.6.3 Change ownership of Prometheus configuration files
      ansible.builtin.file:
        path: "/etc/prometheus/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      with_items: "{{ prometheus_conf_file }}"

    - name: 1.6.4 Change ownership of /var/lib/prometheus
      ansible.builtin.file:
        path: /var/lib/prometheus
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        recurse: yes

    - name: 1.6.7 Copy prometheus.service
      template:
        src: "templates/{{ item }}.j2"
        dest: "/{{ item }}"
        mode: '0744'
      with_items: 
        - "{{ prometheus_template_service_systemd }}"
        - "{{ prometheus_template_prometheus_yml }}"

    - name: 1.6.8 Change ownership of Prometheus /etc/prometheus/prometheus.yml
      ansible.builtin.file:
        path: "/etc/prometheus/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      with_items: "{{ prometheus_service_conf_file }}"
  become: true

- name: 1.7 Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: 1.9 Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
  become: true

- name: 1.10 Open 9090 in firewall
  ansible.builtin.command:
    cmd: ufw allow 9090/tcp
  become: true