---
# tasks file for prometheus
- name: 1.0 Create Prometheus user and group
  block:
    - name: 1.0.1 Create Prometheus group
      ansible.builtin.group:
        name: prometheus
        system: yes

    - name: 1.0.2 Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        system: yes
        shell: /sbin/nologin
        group: prometheus
  become: yes

- name: 1.1 Create /etc/prometheus directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: 1.2 Create /var/lib/prometheus directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'

- name: 1.3 Download prometheus
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp/
  ignore_errors: yes
  with_items: "{{ prometheus_download_url }}"
  become: true

- name: 1.4 Extract the binare prometheus files 
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /opt/
    remote_src: yes
  with_items: "{{ prometheus_archive }}"
  become: true
  notify: 
    - Check exit temp file
    - Remove temp file

- name: 1.5 Move binary & Set Owner
  block: 
    - name: 1.5.1 Copy promtool binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      with_items: "{{ prometheus_bin_file }}"
      ignore_errors: true

    - name: 1.5.2 Change ownership of /usr/local/bin/
      ansible.builtin.file:
        path: "/usr/local/bin/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        state: file
      with_items: "{{ prometheus_bin_file }}"
  become: true

- name: 1.6 Move the Configuration Files & Set Owner
  block: 
    - name: 1.6.1 Copy prometheus binary to /etc/prometheus
      ansible.builtin.copy:
        src: "/opt/prometheus-2.43.0.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      with_items: "{{ prometheus_conf_file }}"
      ignore_errors: true

    - name: 1.6.2 Change ownership of /etc/prometheus
      ansible.builtin.file:
        path: /etc/prometheus
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: 1.6.3 Change ownership of Prometheus configuration files
      ansible.builtin.file:
        path: "/etc/prometheus/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        recurse: "{{ item in ['consoles', 'console_libraries'] }}"
      with_items: "{{ prometheus_conf_file[:-1] }}"  # Exclude the last item

    - name: 1.6.4 Change ownership of /var/lib/prometheus
      ansible.builtin.file:
        path: /var/lib/prometheus
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        recurse: yes

    - name: 1.6.5 Copy prometheus.service
      template:
        src: "templates/{{ prometheus_template_dest }}/{{ prometheus_service_name }}".j2
        dest: /etc/systemd/system
        mode: '0744'

    - name: 1.6.8 Restart prometheus service
      ansible.builtin.command:
        cmd: "service prometheus restart"
      ignore_errors: true
  become: true

