---
# main file for prometheus
- name: Configurate prometheus
  include_tasks: configurate_prometheus.yml
  vars:
    ansible_python_interpreter: "{{ prometheus_python_interpreter }}"

- name: Configurate node_exporter
  include_tasks: configurate_node_exporter.yml
  vars:
    ansible_python_interpreter: "{{ prometheus_python_interpreter }}"