---
# main file for prometheus
- name: 1.0 Install and setting prometheus
  include_tasks: prometheus.yml

# - name: 2.0 Install and setting Victoria Metrics
#   include_tasks: victoriametrics.yml
#   when: inventory_hostname == prometheus_host_machine