---
# prometheus file for prometheus
- name: 1.1 Gatrher network facts
  setup:

- name: 1.2 Create Prometheus user and group
  block:
    - name: 1.2.1 Create Prometheus group
      ansible.builtin.group:
        name: "{{ prometheus_group }}"
        system: yes

    - name: 1.2.2 Create Prometheus user
      ansible.builtin.user:
        name: "{{ prometheus_user }}"
        system: yes
        shell: /sbin/nologin
        group: prometheus
  become: true

- name: "1.3 Create {{ prometheus_conf_dir }} directory"
  file:
    path: "{{ prometheus_conf_dir }}"
    state: directory
    mode: '0755'

- name: "1.4 Create {{ prometheus_lib_dir }} directory"
  file:
    path: "{{ prometheus_lib_dir }}"
    state: directory
    mode: '0755'

- name: 1.5 Download prometheus
  get_url:
    url: "{{ item }}"
    dest: "{{ prometheus_archive }}"
  ignore_errors: yes
  with_items: "{{ prometheus_download_url }}"
  become: true

- name: 1.6 Extract the binare prometheus files 
  unarchive:
    src: "{{ item }}"
    dest: /opt/
    remote_src: yes
  ignore_errors: yes
  with_items: "{{ prometheus_archive }}"
  become: true

- name: 1.7 Check exist temp file
  ansible.builtin.stat:
    path: "{{ prometheus_archive }}"
  register: prometheus_file

- name: 1.8 Remove temp file
  ansible.builtin.file:
    path: "{{ prometheus_archive }}"
    state: absent
  when: prometheus_file.stat.exists

- name: 1.9 Move binary & Set Owner
  block: 
    - name: "1.9.1 Copy promtool binary to {{ prometheus_service_bin_dir }}"
      ansible.builtin.copy:
        src: "{{prometheus_system_dir}}/{{ item }}"
        dest: "{{ prometheus_service_bin_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      with_items: "{{ prometheus_bin_file }}"
      ignore_errors: true

    - name: "1.9.2 Change ownership of {{ prometheus_service_bin_dir }}/"
      ansible.builtin.file:
        path: "{{ prometheus_service_bin_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        state: file
      with_items: "{{ prometheus_bin_file }}"
  become: true

- name: 1.10 Move the Configuration Files & Set Owner
  block: 
    - name: 1.10.1 Create SSL directory
      file:
        path: "{{ prometheus_ssl_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0744'

    - name: 1.10.2 Check if SSL certificate for prometheus exists
      ansible.builtin.stat:
        path: "{{ prometheus_ssl_dir }}/{{ prometheus_ssl_crt }}"
      register: ssl_cert_stat

    - name: 1.10.3 Generate SSL certificate and key for prometheus
      ansible.builtin.shell: >
        openssl req -new -newkey rsa:4096 -days 365 -nodes -x509
        -keyout "{{ prometheus_ssl_dir }}/{{ prometheus_ssl_key }}"
        -out "{{ prometheus_ssl_dir }}/{{ prometheus_ssl_crt }}"
        -subj "/C=RU/ST=Moskovskaya oblast/L=Moscow/O={{ prometheus_name }}/CN={{ ansible_hostname }}"
        -addext "subjectAltName=DNS:localhost,DNS:{{ ansible_hostname }}"
      args:
        chdir: "{{ prometheus_ssl_dir }}"

    - name: 1.10.4 Copy prometheus ssl options file
      template:
        src: "templates/etc/default/{{ prometheus_ssl_network_conf }}.j2"
        dest: "/{{ prometheus_ssl_dir }}/{{ prometheus_ssl_network_conf }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0744'

    - name: "1.10.5 Copy prometheus binary to {{ prometheus_conf_dir }}"
      ansible.builtin.copy:
        src: "{{prometheus_system_dir}}/{{ item }}"
        dest: "{{ prometheus_conf_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      with_items: "{{ prometheus_conf_file }}"
      ignore_errors: true

    - name: "1.10.6 Change ownership of {{ prometheus_conf_dir }}"
      ansible.builtin.file:
        path: "{{ prometheus_conf_dir }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"

    - name: 1.10.7 Change ownership of Prometheus configuration files
      ansible.builtin.file:
        path: "{{ prometheus_conf_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      with_items: "{{ prometheus_conf_file }}"

    - name: "1.10.8 Change ownership of {{ prometheus_lib_dir }}"
      ansible.builtin.file:
        path: "{{ prometheus_lib_dir }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        recurse: yes

    - name: 1.10.9 Copy prometheus.service
      template:
        src: "templates/{{ item }}.j2"
        dest: "/{{ item }}"
        mode: '0744'
      with_items: 
        - "{{ prometheus_template_service_systemd }}"
        - "{{ prometheus_template_prometheus_yml }}"

    - name: 1.10.10 Change ownership of Prometheus {{ prometheus_conf_dir }}/prometheus.yml
      ansible.builtin.file:
        path: "{{ prometheus_conf_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      with_items: "{{ prometheus_service_conf_file }}"

    - name: "1.10.11 Change file permissions in {{ prometheus_ssl_dir }}"
      file:
        path: "{{ prometheus_ssl_dir }}"
        mode: '0744'
        recurse: yes
  become: true

- name: 1.11 Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: 1.12 Enable and start Prometheus service
  ansible.builtin.systemd:
    name: "{{ prometheus_service_name }}"
    state: started
    enabled: yes
  become: true

- name: 1.13 Open 9090 in firewall
  ansible.builtin.command:
    cmd: ufw allow 9090/tcp
  become: true

- name: 1.14 Check prometheus service 
  shell: "{{ prometheus_check_service_status }}"
  register: prometheus_status

- name: 1.15 Debug prometheus
  debug:
    msg:
      - "Prometheus service status: {{ prometheus_status.stdout }}"
      - "Prometheus will opened on: https://{{ ansible_hostname }}:{{ prometheus_port }}"
      #- "Prometheus will opened on: https://{{ ansible_default_ipv4.address }}:{{ prometheus_port }}"
