---
#victoriametrics file for prometheus
- name: 3.1 Open 8428 port fo vistoria metrics
  shell: iptables -I INPUT -p tcp --dport 8428 -j ACCEPT
  become: true

- name: 3.2 Save network result
  shell: "{{ item }}"
  loop:
    # - apt install iptables-persistent -y сделать обработчик для согласия 
    - netfilter-persistent save

- name: 3.3 Download file from artifactory
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /tmp/
  ignore_errors: yes
  with_items: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.102.1/victoria-metrics-linux-amd64-v1.102.1.tar.gz
  become: true

- name: 3.4 Create victoriametrics group
  ansible.builtin.group:
    name: victoriametrics
    system: yes

- name: 3.5 Create victoriametrics user
  ansible.builtin.user:
    name: victoriametrics
    system: yes
    shell: /sbin/nologin
    group: prometheus
  
- name: 3.6 Create var_dir and run_dir directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ prometheus_victoriametrics_user }}"
    group: "{{ prometheus_victoriametrics_group }}"
  loop:
    - "{{ prometheus_victoriametrics_var_dir }}"
    - "{{ prometheus_victoriametrics_run_dir }}"

- name: 3.7 Рекурсивно установить владельца и группу для папки {{ prometheus_victoriametrics_var_dir }}
  file:
    path: "{{ prometheus_victoriametrics_var_dir }}"
    owner: victoriametrics
    group: victoriametrics
    mode: '0755'
    recurse: yes

- name: 3.8 Рекурсивно установить владельца и группу для файла  {{ prometheus_victoriametrics_bin_dir }}/victoria-metrics-prod
  file:
    path: "{{ prometheus_victoriametrics_bin_dir }}/victoria-metrics-prod"
    owner: victoriametrics
    group: victoriametrics
    mode: '0755'

- name: 3.9 Extract the binare nifi files 
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ prometheus_victoriametrics_bin_dir }}"
    remote_src: yes
  with_items: /tmp/victoria-metrics-linux-amd64-v1.102.1.tar.gz
  become: true

- name: 3.10 Copy victoriametrics.service
  template:
    src: "templates/{{ item }}.j2"
    dest: "/{{ item }}"
    mode: '0755'
  with_items: 
    - "{{ prometheus_template_victoriametrics_service_systemd_node }}"
  become: true

- name: 3.11 Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: 3.12 Enable and start victoriametrics service
  ansible.builtin.systemd:
    name: victoriametrics
    state: started
    enabled: yes
  become: true

- name: 3.13 Check victoriametrics service start
  shell: "{{ prometheus_victoriametrics_status }}"
  register: victoriametrics_status

- name: 3.14 Debug check victoriametrics service start
  debug:
    msg: "{{ victoriametrics_status }}"